
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: 770380002756.dkr.ecr.us-east-1.amazonaws.com/django-k8s-demo:${BUILD_NUMBER}
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: django-config
        livenessProbe:
          httpGet:
            path: /api/demo/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /api/demo/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
